### ISSUE TITLE
Changed the code to allow class names

### ISSUE THREAD

**Issue by Verhoeckx** [psalmody/html-contents#3]
Hi Michael Tallino,

I had a situation in which I wanted to have two Table of contents on one page. To achieve this I changed the following code:

I replaced
`let TOC = document.getElementById(toc.replace(/\#/g, ''))`

with
`let TOCS = document.querySelectorAll(toc);`
  
and I replaced
`TOC.insertAdjacentHTML('beforeend', html)`
  
with 
```
for (var i = 0; i < TOCS.length; i++) {
    TOCS[i].insertAdjacentHTML('beforeend', html);
}
```
Now you can use a class name to add the (multiple) table of content to. It makes your script a little bit more flexible I belief.

Good luck with the singing :-)!

Verhoeckx

**Comment by psalmody** [comment]
Great idea. I've just fixed that, pushing a new release too. 👍
