### ISSUE TITLE
Can I nest h3 below h2 lists? 

### ISSUE THREAD

**Issue by filip-van-hoeckel** [psalmody/html-contents#5]
This is the current code being output
`ul>h2,h2,h3`
How would we go about?
`ul>h2,h2>ul,h3`
This enables us to use the active class in order to hide a submenu when the parent is not active.

**Comment by psalmody** [comment]
I'm not quite following - can you give a short example? The tool doesn't output h2 or h3 tags so I'm not sure what you mean... are you wanting the output to be nested differently? Or is it having trouble picking up one of your headings?

**Comment by filip-van-hoeckel** [comment]
Sorry bout that: allow me to demonstrate: #
https://gist.github.com/filip-van-hoeckel/0f37711def15a6fdac9dbc3af985e250

**Comment by psalmody** [comment]
Can you send the javascript code you're using too? When I run the test scenarios I have, the toc matches what you are requesting:

![image](https://user-images.githubusercontent.com/12420157/107785304-a678cd00-6d09-11eb-9ef6-06c0559efb28.png)

See example at: https://github.com/psalmody/html-contents/blob/master/test/index.html

Initializing with:

```js
    document.addEventListener("DOMContentLoaded", function(event) {
      htmlContents('#toc', {
        bottom: 5,
        listType: 'o',
        filter: function(arr) {
          return !arr.matches('.noOutline')
        }
      })
    })
```
